AWSTemplateFormatVersion: 2010-09-09
Description: >-
  (qs-1nae6brn2) HashiCorp Consul+Nomad+VPC, License: Apache 2.0 (Please do not
  remove) Aug,16,2017
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: VPC Network Configuration
        Parameters:
          - AvailabilityZones
          - VPCCIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PublicSubnet3CIDR
          - AccessCIDR
      - Label:
          default: Node Access Configuration
        Parameters:
          - KeyPairName
      - Label:
          default: Nomad Cluster Setup
        Parameters:
          - NomadInstanceType
          - NomadServerNodes
          # - PrivateNomadClientNodes
          # - MinPrivateNomadClientNodes
      # - Label:
      #     default: Consul Setup
      #   Parameters:
      #     - ConsulClientNodes
      #     - ConsulServerNodes
      #     - ConsulInstanceType
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: VPC CIDR
      # ConsulInstanceType:
      #   default: Consul Instance Type
      # ConsulServerNodes:
      #   default: Consul Server Nodes
      # ConsulClientNodes:
      #   default: Consul Client Nodes

      # MinPrivateNomadClientNodes:
      #   default: Minimum Private Nomad Client Nodes
      # PrivateNomadClientNodes:
      #   default: Private Nomad Client Nodes
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private Subnet 3 CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public Subnet 3 CIDR
      AccessCIDR:
        default: Permitted IP range
      KeyPairName:
        default: Key Name
      NomadServerNodes:
        default: Nomad Server Nodes
      NomadInstanceType:
        default: Nomad Instance Type
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix

Parameters:
  EnvironmentName:
    Type: String
    Description: >-
      Environment name to use for the generated environment. This is used as a
      tags applied to the generated resources.
  AccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: >-
      The CIDR IP range that is permitted to access the Nomad or Consul nodes.
      Note: a value of 0.0.0.0/0 will allow access from ANY ip address
    Type: String
  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC. Note: The
      logical order is preserved (3 AZs are used for this deployment)
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  # ConsulClientNodes:
  #   Default: '0'
  #   Description: >-
  #     Sets the desired capacity and maximum size for the Consul client node
  #     cluster
  #   Type: String
  # ConsulInstanceType:
  #   AllowedValues:
  #     - t2.micro
  #     - t2.small
  #     - t2.medium
  #     - t2.large
  #     - m4.large
  #     - m4.xlarge
  #     - m4.2xlarge
  #     - m4.4xlarge
  #     - m4.10xlarge
  #     - m3.medium
  #     - m3.large
  #     - m3.xlarge
  #     - m3.2xlarge
  #     - c4.large
  #     - c4.xlarge
  #     - c4.2xlarge
  #     - c4.4xlarge
  #     - c4.8xlarge
  #     - c3.large
  #     - c3.xlarge
  #     - c3.2xlarge
  #     - c3.4xlarge
  #     - c3.8xlarge
  #     - r3.large
  #     - r3.xlarge
  #     - r3.2xlarge
  #     - r3.4xlarge
  #     - r3.8xlarge
  #     - i2.xlarge
  #     - i2.2xlarge
  #     - i2.4xlarge
  #     - i2.8xlarge
  #   ConstraintDescription: Choose an instance type. m3.medium or larger recommended.
  #   Default: t2.medium
  #   Description: Consul node instance type
  #   Type: String
  # ConsulServerNodes:
  #   AllowedValues:
  #     - '3'
  #     - '5'
  #     - '7'
  #   Default: '3'
  #   Description: >-
  #     Sets the desired capacity and maximum size for the Consul Server node
  #     cluster. Values recommended are: 3, 5, and 7
  #   Type: String
  KeyPairName:
    Description: >-
      Public/private key pairs allow you to securely connect to your instance
      after it launches
    Type: 'AWS::EC2::KeyPair::KeyName'
  # MinPrivateNomadClientNodes:
  #   Default: '1'
  #   Description: Sets the minimum number of Nomad client nodes for the ASG to keep running.
  #   Type: String
  NomadInstanceType:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
    ConstraintDescription: Choose an instance type. m4.large or larger recommended.
    Default: m4.large
    Description: Nomad node instance type
    Type: String
  NomadServerNodes:
    AllowedValues:
      - '3'
      - '5'
      - '7'
    Default: '3'
    Description: >-
      Sets the desired capacity and maximum size for the Consul Server node
      cluster. Values recommended are: 3, 5, and 7
    Type: String
  # PrivateNomadClientNodes:
  #   Default: '3'
  #   Description: Sets the initial number of Nomad client nodes for the ASG to start.
  #   Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.64.0/19
    Description: CIDR block for private subnet 3 located in Availability Zone 3.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.128.0/20
    Description: CIDR Block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.144.0/20
    Description: CIDR Block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 10.0.160.0/20
    Description: CIDR Block for the public DMZ subnet 3 located in Availability Zone 3
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-hashicorp-nomad/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String

Conditions:
  GovCloudCondition: !Equals ["us-gov-west-1", !Ref 'AWS::Region']

Resources:
  # HashiCorpConsulStack:
  #   DependsOn: LinuxBastionHostStack
  #   Properties:
  #     Parameters:
  #       BastionSecurityGroupID: !GetAtt LinuxBastionHostStack.Outputs.BastionSecurityGroupID
  #       ConsulClientNodes: !Ref ConsulClientNodes
  #       ConsulInstanceType: !Ref ConsulInstanceType
  #       ConsulServerNodes: !Ref ConsulServerNodes
  #       KeyPair: !Ref KeyPairName
  #       PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
  #       PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
  #       PrivateSubnet3ID: !GetAtt VPCStack.Outputs.PrivateSubnet3AID
  #       VPCCIDR: !Ref VPCCIDR
  #       VPCID: !GetAtt VPCStack.Outputs.VPCID
  #       QSS3BucketName: !Ref QSS3BucketName
  #       QSS3KeyPrefix: !Sub 
  #         - '${QSS3KeyPrefix}submodules/quickstart-hashicorp-consul/'
  #         - QSS3KeyPrefix: !Ref QSS3KeyPrefix
  #     TemplateURL: !Sub 
  #       - >-
  #         https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-hashicorp-consul/templates/quickstart-hashicorp-consul.template
  #       - QSS3Region: !If 
  #           - GovCloudCondition
  #           - s3-us-gov-west-1
  #           - s3
  #   Type: 'AWS::CloudFormation::Stack'
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        NumberOfAZs: '3'
        AvailabilityZones: !Join [',', !Ref AvailabilityZones]
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3ACIDR: !Ref PrivateSubnet3CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        VPCCIDR: !Ref VPCCIDR
      TemplateURL: !Sub 
          - "https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml"
          - QSS3Region: !If [GovCloudCondition, "s3-us-gov-west-1", "s3"]

  LinuxBastionHostStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        BastionAMIOS: Ubuntu-Server-20.04-LTS-HVM
        KeyPairName: !Ref KeyPairName
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}submodules/quickstart-linux-bastion/'
        RemoteAccessCIDR: !Ref AccessCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
      TemplateURL: !Sub
        - "https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template"
        - QSS3Region: !If [GovCloudCondition, "s3-us-gov-west-1", "s3"]

  HashiCorpNomadClusterStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        # MinPrivateNomadClientNodes: !Ref MinPrivateNomadClientNodes
        # PrivateNomadClientNodes: !Ref PrivateNomadClientNodes
        EnvironmentName: !Ref EnvironmentName
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PrivateSubnet3ID: !GetAtt VPCStack.Outputs.PrivateSubnet3AID
        AccessCIDR: !Ref AccessCIDR
        BastionSecurityGroupID: !GetAtt LinuxBastionHostStack.Outputs.BastionSecurityGroupID
        KeyPairName: !Ref KeyPairName
        NomadInstanceType: !Ref NomadInstanceType
        NomadServerNodes: !Ref NomadServerNodes
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TemplateURL: !Sub 
        - "https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/new-quickstart-hashicorp-nomad-cluster.template.yaml"
        - QSS3Region: !If [GovCloudCondition, "s3-us-gov-west-1", "s3"]

Outputs:
  NomadEc2RetryTagKey:
    Value: !GetAtt HashiCorpNomadClusterStack.Outputs.NomadEc2RetryTagKey
    Description: The EC2 instance tag key to filter on when joining to Nomad server nodes.
  NomadEc2RetryTagValue:
    Value: !GetAtt HashiCorpNomadClusterStack.Outputs.NomadEc2RetryTagValue
    Description: The EC2 instance tag value to filter on when joining to Nomad server nodes.



